/*
 * Dibujo.java
 * Form for simulation showing network and packet progress
 */
package jsimured.main;

import java.util.logging.Level;
import java.util.logging.Logger;

public class Dibujo extends javax.swing.JFrame{
    static boolean Paused;

    public Dibujo() {
        setVisible(false);
        initComponents();
        Jsimured.AreaDibujo=AreaDibujo;
        pack();
        setIdioma(Jsimured.Idioma());
        Paused=false;
        new Thread(Temporizador).start();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaBotones = new javax.swing.JPanel();
        PanelSimple = new javax.swing.JPanel();
        RetrasoTxt = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        bPararSimple = new javax.swing.JButton();
        bPaso = new javax.swing.JButton();
        VerNum = new javax.swing.JCheckBox();
        MostrarCheck = new javax.swing.JCheckBox();
        bGoSimple = new javax.swing.JButton();
        PanelMultiple = new javax.swing.JPanel();
        bPararMultiple = new javax.swing.JButton();
        bGoMultiple = new javax.swing.JButton();
        AreaDibujo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Simulation");
        setBounds(new java.awt.Rectangle(0, 0, 1000, 1000));
        setName("Simulacion"); // NOI18N
        setPreferredSize(new java.awt.Dimension(699, 544));
        getContentPane().setLayout(new java.awt.BorderLayout(0, 10));

        AreaBotones.setPreferredSize(new java.awt.Dimension(500, 110));

        PanelSimple.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulación simple o interactiva"));
        PanelSimple.setToolTipText("Simulación simple o interactiva");

        RetrasoTxt.setEditable(true);
        RetrasoTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "100", "200", "500", "1000", "2000" }));
        RetrasoTxt.setSelectedIndex(2);
        RetrasoTxt.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Retraso entre ciclos (ms)");
        jLabel1.setAutoscrolls(true);

        bPararSimple.setText("Terminar");
        bPararSimple.setEnabled(false);
        bPararSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPararSimpleActionPerformed(evt);
            }
        });

        bPaso.setText("Paso a Paso");
        bPaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPasoActionPerformed(evt);
            }
        });

        VerNum.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        VerNum.setSelected(true);
        VerNum.setText("Mostrar nº Flit");
        VerNum.setAutoscrolls(true);
        VerNum.setEnabled(false);
        VerNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerNumActionPerformed(evt);
            }
        });

        MostrarCheck.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        MostrarCheck.setText("Mostrar Evolución");
        MostrarCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarCheckActionPerformed(evt);
            }
        });

        bGoSimple.setText("Simular");
        bGoSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGoSimpleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSimpleLayout = new javax.swing.GroupLayout(PanelSimple);
        PanelSimple.setLayout(PanelSimpleLayout);
        PanelSimpleLayout.setHorizontalGroup(
            PanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSimpleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSimpleLayout.createSequentialGroup()
                        .addComponent(bGoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPaso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelSimpleLayout.createSequentialGroup()
                        .addComponent(bPararSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MostrarCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelSimpleLayout.createSequentialGroup()
                        .addComponent(VerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(PanelSimpleLayout.createSequentialGroup()
                        .addComponent(RetrasoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        PanelSimpleLayout.setVerticalGroup(
            PanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSimpleLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(PanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGoSimple)
                    .addComponent(bPaso)
                    .addComponent(RetrasoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPararSimple)
                    .addComponent(MostrarCheck)
                    .addComponent(VerNum))
                .addGap(3, 3, 3))
        );

        PanelMultiple.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulación Múltiple"));
        PanelMultiple.setToolTipText("");

        bPararMultiple.setText("Terminar");
        bPararMultiple.setEnabled(false);
        bPararMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPararMultipleActionPerformed(evt);
            }
        });

        bGoMultiple.setText("Simular");
        bGoMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGoMultipleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMultipleLayout = new javax.swing.GroupLayout(PanelMultiple);
        PanelMultiple.setLayout(PanelMultipleLayout);
        PanelMultipleLayout.setHorizontalGroup(
            PanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMultipleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bPararMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGoMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        PanelMultipleLayout.setVerticalGroup(
            PanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMultipleLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(bGoMultiple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bPararMultiple)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AreaBotonesLayout = new javax.swing.GroupLayout(AreaBotones);
        AreaBotones.setLayout(AreaBotonesLayout);
        AreaBotonesLayout.setHorizontalGroup(
            AreaBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaBotonesLayout.createSequentialGroup()
                .addComponent(PanelMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AreaBotonesLayout.setVerticalGroup(
            AreaBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaBotonesLayout.createSequentialGroup()
                .addGroup(AreaBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelMultiple, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PanelMultiple.getAccessibleContext().setAccessibleDescription("Simulación Múltiple");

        getContentPane().add(AreaBotones, java.awt.BorderLayout.NORTH);

        AreaDibujo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                AreaDibujoComponentResized(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Network");
        jLabel2.setToolTipText("");
        jLabel2.setPreferredSize(new java.awt.Dimension(446, 51));

        javax.swing.GroupLayout AreaDibujoLayout = new javax.swing.GroupLayout(AreaDibujo);
        AreaDibujo.setLayout(AreaDibujoLayout);
        AreaDibujoLayout.setHorizontalGroup(
            AreaDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        AreaDibujoLayout.setVerticalGroup(
            AreaDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaDibujoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(AreaDibujo, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleParent(this);

        setSize(new java.awt.Dimension(699, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/** Simulacion paso a paso */
    private void bPasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPasoActionPerformed
        Jsimured.JUSTONE=true;
        Paused=true;
        if (Jsimured.Idioma()==0) bGoSimple.setText("Continuar");    
        else  bGoSimple.setText("Continue");
        if (Jsimured.SimuStop)
        {
            Jsimured.SimuControl.Write(1); // se para
            new Thread(Jsimured.Simular).start();
        }
        else
        {
            Jsimured.SimuControl.Write(1); // se para              
        }      
    }//GEN-LAST:event_bPasoActionPerformed

/** Ver numero de paquete */
    private void VerNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerNumActionPerformed
        if (VerNum.isSelected()){
            Jsimured.vernum = 1;
        }
        else
            Jsimured.vernum = 0;
    }//GEN-LAST:event_VerNumActionPerformed

    private void bPararSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPararSimpleActionPerformed
        Paused=false;
        Jsimured.SimuControl.Write(3);             
    }//GEN-LAST:event_bPararSimpleActionPerformed

    private void MostrarCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarCheckActionPerformed
        // TODO add your handling code here:
        //RetrasoTxt.setEnabled(MostrarCheck.isSelected());
        //VerNum.setEnabled(MostrarCheck.isSelected());
        if (MostrarCheck.isSelected()) Jsimured.SimuControl.Write(1); // manda 1 para que vaya a pasos temporizados
        else if (!Paused) Jsimured.SimuControl.Write(0); // manda 0 para que siga a toda velocidad
    }//GEN-LAST:event_MostrarCheckActionPerformed

    private void bGoSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGoSimpleActionPerformed
        // TODO add your handling code here:

        Jsimured.JUSTONE=true;
        if (Jsimured.SimuStop)
        {
            Paused=false;
            if (Jsimured.Idioma()==0) bGoSimple.setText("Pausar");    
            else  bGoSimple.setText("Pause");
            if (MostrarCheck.isSelected()){
                Jsimured.SimuControl.Write(1);       
            }
            else{
                Jsimured.SimuControl.Write(0);
            }
            new Thread(Jsimured.Simular).start();
        }
        else
        {
            Paused=!Paused;
            if (!Paused)
            {
                //Jsimured.SimuControl.Write(0);
                if (Jsimured.Idioma()==0) bGoSimple.setText("Pausar");    
                else  bGoSimple.setText("Pause");
            }
            else
            {
                //Jsimured.SimuControl.Write(1);
                if (Jsimured.Idioma()==0) bGoSimple.setText("Continuar");    
                else  bGoSimple.setText("Continue");
            }
        }
    }//GEN-LAST:event_bGoSimpleActionPerformed

    private void bPararMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPararMultipleActionPerformed
        // TODO add your handling code here:
            Jsimured.SimuControl.Write(3);
    }//GEN-LAST:event_bPararMultipleActionPerformed

    private void bGoMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGoMultipleActionPerformed
        // TODO add your handling code here:
        
        //PanelSimple.setEnabled(false);
        if (Jsimured.SimuStop)
        {
            Paused=false;
            Jsimured.SimuControl.Write(0);
            Jsimured.JUSTONE=false;
            if (Jsimured.Idioma()==0) bGoMultiple.setText("Pausar"); 
            else bGoMultiple.setText("Pause"); 
            new Thread(Jsimured.Simular).start();
        }
        else
        {
            if (Jsimured.SimuControl.Read()==0)
            {
                Paused=true;
                Jsimured.SimuControl.Write(1); // pausar
                if (Jsimured.Idioma()==0) bGoMultiple.setText("Continuar");
                else bGoMultiple.setText("Continue");
            }
            else
            {
                Paused=false;
                Jsimured.SimuControl.Write(0); // Continuar
                if (Jsimured.Idioma()==0) bGoMultiple.setText("Pausar"); 
                else bGoMultiple.setText("Pause"); 
            }
        }
    }//GEN-LAST:event_bGoMultipleActionPerformed

    private void AreaDibujoComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_AreaDibujoComponentResized
        // TODO add your handling code here:
        //AreaDibujo.repaint();
        //AreaDibujo.paintComponents(AreaDibujo.getGraphics());
    }//GEN-LAST:event_AreaDibujoComponentResized
    
    public static void setIdioma (int idioma){
        switch(idioma){
            case 0: // Spanish
                bGoMultiple.setText("Simular");
                bGoSimple.setText("Simular");
                //bPausa.setText("Pausa");
                bPaso.setText("Paso a Paso");
                bPararSimple.setText("Terminar");
                bPararMultiple.setText("Terminar");
                MostrarCheck.setText("Mostrar Evolución");
                VerNum.setText("Mostrar n. Flit");
                jLabel1.setText("Retraso entre ciclos (ms)");
                PanelMultiple.setBorder(new javax.swing.border.TitledBorder("Simulación Múltiple"));
                PanelSimple.setBorder(new javax.swing.border.TitledBorder("Simulación Simple o Interactiva"));
                break;
            case 1: // English
                bGoMultiple.setText("Simulate");
                bGoSimple.setText("Simulate");
                //bPausa.setText("Pause");
                bPaso.setText("Step simulate");
                bPararSimple.setText("Stop");
                bPararMultiple.setText("Stop");
                MostrarCheck.setText("Show Evolution");
                VerNum.setText("Show Flit Number");
                jLabel1.setText("Cycle Delay (ms)");
                PanelMultiple.setBorder(new javax.swing.border.TitledBorder("Multiple Simulation"));
                PanelSimple.setBorder(new javax.swing.border.TitledBorder("Single or Interactive Simulation"));
                break;
            default:;
        }
  }

  public static Runnable Temporizador = new Runnable() {   
        @Override
    public synchronized void run() {       
      int espera;
      while (true)
      {
          if (MostrarCheck.isSelected() && Jsimured.JUSTONE && !Jsimured.SimuStop)
          {
            espera=Integer.parseInt(RetrasoTxt.getSelectedItem().toString());
            if (espera>0)
            {
                    try {
                        wait(espera);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Dibujo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (!Paused) Jsimured.SimuControl.Write(1);
            }
            else
            {
                    try {
                        wait(1);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Dibujo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (!Paused) Jsimured.SimuControl.Write(1);
            }
          }
          else
          {
                    try {
                        wait(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Dibujo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (!Paused) Jsimured.SimuControl.Write(0); // Para que no se pare aqui
          }
      }
  }
};
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AreaBotones;
    private javax.swing.JPanel AreaDibujo;
    public static javax.swing.JCheckBox MostrarCheck;
    public static javax.swing.JPanel PanelMultiple;
    public static javax.swing.JPanel PanelSimple;
    public static javax.swing.JComboBox RetrasoTxt;
    public static javax.swing.JCheckBox VerNum;
    public static javax.swing.JButton bGoMultiple;
    public static javax.swing.JButton bGoSimple;
    public static javax.swing.JButton bPararMultiple;
    public static javax.swing.JButton bPararSimple;
    public static javax.swing.JButton bPaso;
    public static javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
}
